repositories:
- name: linkerd
  url: https://helm.linkerd.io/stable

releases:
- name: linkerd-viz
  namespace: linkerd-viz
  createNamespace: false
  chart: linkerd/linkerd-viz
  version: 2.11.0
  values:
  - values.yaml
  hooks:
  - events: ["presync"]
    showlogs: true
    command: kubectl
    args: ["apply", "-f", "ns-linkerd-viz.yaml"]
  - events: ["postuninstall"]
    showlogs: true
    command: kubectl
    args: ["delete", "-f", "ns-linkerd-viz.yaml"]
