repositories:
- name: linkerd-edge
  url: https://helm.linkerd.io/edge

releases:
- name: linkerd-viz
  namespace: linkerd-viz
  createNamespace: true
  chart: linkerd-edge/linkerd-viz
  version: "21.12.3"
  needs:
  - linkerd-control-plane
  hooks:
  - events: ["presync"]
    showlogs: true
    command: kubectl
    args: ["wait", "--for=condition=available", "deploy/linkerd-proxy-injector", "-n", "linkerd", "--timeout=3m"]
  # - events: ["postuninstall"]
  #   showlogs: true
  #   command: kubectl
  #   args: ["delete", "-f", "ns-linkerd-viz.yaml"]
