repositories:
- name: linkerd
  url: https://helm.linkerd.io/stable
- name: linkerd-edge
  url: https://helm.linkerd.io/edge

releases:
- name: linkerd-viz
  namespace: linkerd-viz
  createNamespace: true
  chart: linkerd-edge/linkerd-viz
  # https://github.com/linkerd/linkerd  2/blob/edge-24.1.3/viz/charts/linkerd-viz/Chart.yaml
  version: 30.14.6-edge
  values:
  - dashboard:
      enforcedHostRegexp: linkerd-viz.local
  hooks:
  - events: ["presync"]
    showlogs: true
    command: kubectl
    args: ["wait", "deploy/linkerd-proxy-injector", "-n=linkerd", "--for=condition=available", "--timeout=3m"]
  - events: ["postsync"]
    showlogs: true
    command: kubectl
    args: ["apply", "-f", "ingress.yaml"]
