repositories:
- name: linkerd
  url: https://helm.linkerd.io/stable
- name: linkerd-edge
  url: https://helm.linkerd.io/edge

releases:
- name: linkerd-viz
  namespace: linkerd-viz
  createNamespace: true
  chart: linkerd/linkerd-viz
  # https://github.com/linkerd/linkerd2/blob/stable-2.12.2/viz/charts/linkerd-viz/Chart.yaml
  version: 30.3.5
  hooks:
  - events: ["presync"]
    showlogs: true
    command: kubectl
    args: ["wait", "--for=condition=available", "deploy/linkerd-proxy-injector", "-n", "linkerd", "--timeout=3m"]
  # - events: ["postuninstall"]
  #   showlogs: true
  #   command: kubectl
  #   args: ["delete", "-f", "ns-linkerd-viz.yaml"]
