---
###
### Linkerd Viz Extension Namespace
###
kind: Namespace
apiVersion: v1
metadata:
  name: linkerd-viz
  labels:
    linkerd.io/extension: viz
  annotations:
    # viz.linkerd.io/external-prometheus: {{.Values.prometheusUrl}}
    linkerd.io/inject: enabled
