repositories:
- name: linkerd
  url: https://helm.linkerd.io/stable

releases:
- name: linkerd2
  namespace: linkerd
  createNamespace: false
  chart: linkerd/linkerd2
  version: 2.11.1
  values:
  - values.yaml
  #- values-ha.yaml
  - crtexpiry.yaml
  set:
  - name: identityTrustAnchorsPEM
    file: ca.crt
  - name: identity.issuer.tls.crtPEM
    file: issuer.crt
  - name: identity.issuer.tls.keyPEM
    file: issuer.key
  hooks:
  - events: ["presync"]
    showlogs: true
    command: kubectl
    args: ["apply", "-f", "ns-linkerd.yaml"]
  - events: ["postuninstall"]
    showlogs: true
    command: kubectl
    args: ["delete", "-f", "ns-linkerd.yaml"]
