repositories:
- name: linkerd
  url: https://helm.linkerd.io/stable
- name: linkerd-edge
  url: https://helm.linkerd.io/edge

releases:
- name: linkerd-control-plane
  namespace: linkerd
  createNamespace: false
  chart: linkerd-edge/linkerd-control-plane
  # https://github.com/linkerd/linkerd2/blob/edge-24.5.5/charts/linkerd-control-plane/Chart.yaml
  version: 2024.5.5
  set:
  - name: identityTrustAnchorsPEM
    file: ca.crt
  - name: identity.issuer.tls.crtPEM
    file: issuer.crt
  - name: identity.issuer.tls.keyPEM
    file: issuer.key
