repositories:
- name: linkerd
  url: https://helm.linkerd.io/stable
- name: linkerd-edge
  url: https://helm.linkerd.io/edge

releases:
- name: linkerd-control-plane
  namespace: linkerd
  createNamespace: false
  chart: linkerd-edge/linkerd-control-plane
  # https://github.com/linkerd/linkerd2/blob/edge-23.10.4/charts/linkerd-control-plane/Chart.yaml
  version: 1.17.5-edge
  set:
  - name: identityTrustAnchorsPEM
    file: ca.crt
  - name: identity.issuer.tls.crtPEM
    file: issuer.crt
  - name: identity.issuer.tls.keyPEM
    file: issuer.key
