repositories:
- name: linkerd
  url: https://helm.linkerd.io/stable
- name: linkerd-edge
  url: https://helm.linkerd.io/edge

releases:
- name: linkerd-control-plane
  namespace: linkerd
  createNamespace: false
  chart: linkerd-edge/linkerd-control-plane
  # https://github.com/linkerd/linkerd2/blob/edge-24.2.5/charts/linkerd-control-plane/Chart.yaml
  version: 1.18.11-edge
  set:
  - name: identityTrustAnchorsPEM
    file: ca.crt
  - name: identity.issuer.scheme
    value: kubernetes.io/tls
