repositories:
- name: linkerd
  url: https://helm.linkerd.io/stable
- name: linkerd-edge
  url: https://helm.linkerd.io/edge

releases:
- name: linkerd-crds
  namespace: linkerd
  createNamespace: true
  chart: linkerd-edge/linkerd-crds
  # https://github.com/linkerd/linkerd2/blob/edge-23.11.4/charts/linkerd-crds/Chart.yaml
  version: 1.9.0-edge
