repositories:
- name: podinfo
  url: https://stefanprodan.github.io/podinfo

releases:
- name: backend-a
  namespace: test
  chart: podinfo/podinfo
  createNamespace: false
  version: 6.6.1
  values:
  - ui:
      message: A backend
  hooks:
  - events: ["presync"]
    showlogs: true
    command: kubectl
    args: ["apply", "-f", "namespace.yaml"]

- name: backend-b
  namespace: test
  chart: podinfo/podinfo
  createNamespace: false
  version: 6.6.1
  values:
  - ui:
      message: B backend

- name: frontend
  namespace: test
  chart: podinfo/podinfo
  createNamespace: false
  version: 6.6.1
  values:
  - backend: http://backend-a-podinfo:9898/env
  - ingress:
      enabled: true
      className: traefik
