name: test

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.5.0

      - uses: aquaproj/aqua-installer@v2.0.2
        with:
          aqua_version: v1.37.2

      - run: |
          step certificate create root.linkerd.cluster.local linkerd-control-plane/ca.crt linkerd-control-plane/ca.key \
          --profile root-ca --no-password --insecure

      - run: |
          step certificate create identity.linkerd.cluster.local linkerd-control-plane/issuer.crt linkerd-control-plane/issuer.key \
          --profile intermediate-ca --not-after 8760h --no-password --insecure \
          --ca linkerd-control-plane/ca.crt --ca-key linkerd-control-plane/ca.key

      - run: helmfile -f helmfile.yaml sync

      - run: kubectl wait deploy -A --for condition=Available=True -l app.kubernetes.io/part-of=Linkerd

      - run: linkerd check
