name: test

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: mikutas/my-aqua-installer@v0.2.0

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.8.0

      - run: just ca

      - run: just issuer

      - run: helm plugin install https://github.com/databus23/helm-diff

      - run: just apply-all

      - run: kubectl wait deploy -A -l app.kubernetes.io/part-of=Linkerd --for condition=available --timeout 3m

      - run: linkerd check
        env:
          AQUA_X_SYS_EXEC: false

  diff:
    strategy:
      matrix:
        release-name: [linkerd-control-plane, linkerd-crds, linkerd-viz]
    uses: mikutas/helmfiles/.github/workflows/reusable-diff.yml@main
    with:
      release-name: ${{ matrix.release-name }}
