name: Linkerd

on: pull_request

jobs:
  certificates:
    runs-on: ubuntu-latest
    steps:
      - uses: mikutas/my-aqua-installer@main
      - run: just ca
      - run: just issuer
      - uses: actions/upload-artifact@v4
        with:
          name: certs
          path: |
            linkerd-control-plane/*.crt
            linkerd-control-plane/*.key

  test:
    needs: ["certificates"]
    runs-on: ubuntu-latest
    steps:
      - uses: mikutas/my-aqua-installer@main

      - name: Create k8s Cluster
        run: just create-cluster

      - run: helm plugin install https://github.com/databus23/helm-diff

      - uses: actions/download-artifact@v4
        with:
          name: certs
          path: linkerd-control-plane

      - run: just apply-all

      - run: kubectl wait deploy -A -l app.kubernetes.io/part-of=Linkerd --for condition=available --timeout 3m

      - run: linkerd check
        env:
          AQUA_X_SYS_EXEC: false

  diff:
    needs: ["certificates"]
    strategy:
      matrix:
        release-name: [linkerd-control-plane, linkerd-crds, linkerd-viz]
        include:
          - release-name: linkerd-control-plane
            artifact-dl-name: certs
            artifact-dl-path: linkerd-control-plane
    uses: mikutas/helmfiles/.github/workflows/reusable-diff.yml@main
    with:
      changed-dir: ${{ matrix.release-name }}
      artifact-dl-name: ${{ matrix.artifact-dl-name }}
      artifact-dl-path: ${{ matrix.artifact-dl-path }}

  polaris:
    needs: ["diff"]
    strategy:
      matrix:
        release-name: [linkerd-control-plane, linkerd-crds, linkerd-viz]
    uses: mikutas/helmfiles/.github/workflows/reusable-polaris.yml@main
    with:
      changed-dir: ${{ matrix.release-name }}

  status-check:
    runs-on: ubuntu-latest
    needs:
    - certificates
    - diff
    - test
    permissions: {}
    if: failure()
    steps:
      - run: exit 1
