name: test

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.6.0

      - uses: aquaproj/aqua-installer@v2.1.1
        with:
          aqua_version: v2.7.0

      - run: |
          step certificate create root.linkerd.cluster.local linkerd-control-plane/ca.crt linkerd-control-plane/ca.key \
          --profile root-ca --no-password --insecure

      - run: |
          step certificate create identity.linkerd.cluster.local linkerd-control-plane/issuer.crt linkerd-control-plane/issuer.key \
          --profile intermediate-ca --not-after 8760h --no-password --insecure \
          --ca linkerd-control-plane/ca.crt --ca-key linkerd-control-plane/ca.key

      - run: helmfile -f helmfile.yaml sync

      - run: kubectl wait deploy -A -l app.kubernetes.io/part-of=Linkerd --for condition=available --timeout 3m

      - run: linkerd check
        env:
          AQUA_X_SYS_EXEC: false
